version: '3'
services:
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./db_data/mysql_data:/var/lib/mysql
    env_file:
      - .env/development/database

  books:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      RAILS_ENV: development
    env_file:
      - .env/development/database
    depends_on:
      - mysql

